name: geopy-service

services:
  geo-api:
    image: geopy_api
    container_name: geo-api
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__AppDbContext: Host=db;Port=5432;Username=postgres;Password=postgres;Database=geopy_db
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: geo-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geopy_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d userdb" ]
      timeout: 5s
      interval: 5s
      retries: 5
         
volumes:
  postgres_data: